# for anaconda/mamba
# mamba env create -f environment.yaml
# can also update and then run:
# mamba env update -n basicserve --file environment.yaml    
name: basicserve

channels:
  - pytorch 
  - nvidia
  - conda-forge
  
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  ## serving
  - uvicorn
  - fastapi
  - pydantic
  ## pytorch ones
  - pytorch # should be >= 2
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8 ## comment out if not in cuda env.
  - pip:
    - ray[default,data]>=2.5.0
    - transformers
    - pandas
    - pyarrow
    - accelerate
    - sentencepiece
